services:
  plugin.manager.feeds.manager:
    class: Drupal\feeds\Plugin\Type\FeedsPluginManager
    arguments: ['manager', '@container.namespaces', '@cache.cache', '@language_manager', '@module_handler']
  plugin.manager.feeds.scheduler:
    class: Drupal\feeds\Plugin\Type\FeedsPluginManager
    arguments: ['scheduler', '@container.namespaces', '@cache.cache', '@language_manager', '@module_handler']
  plugin.manager.feeds.fetcher:
    class: Drupal\feeds\Plugin\Type\FeedsPluginManager
    arguments: ['fetcher', '@container.namespaces', '@cache.cache', '@language_manager', '@module_handler']
  plugin.manager.feeds.parser:
    class: Drupal\feeds\Plugin\Type\FeedsPluginManager
    arguments: ['parser', '@container.namespaces', '@cache.cache', '@language_manager', '@module_handler']
  plugin.manager.feeds.processor:
    class: Drupal\feeds\Plugin\Type\FeedsPluginManager
    arguments: ['processor', '@container.namespaces', '@cache.cache', '@language_manager', '@module_handler']
  plugin.manager.feeds.source:
    class: Drupal\feeds\Plugin\Type\FeedsPluginManager
    arguments: ['source', '@container.namespaces', '@cache.cache', '@language_manager', '@module_handler']
  plugin.manager.feeds.target:
    class: Drupal\feeds\Plugin\Type\FeedsPluginManager
    arguments: ['target', '@container.namespaces', '@cache.cache', '@language_manager', '@module_handler']
  plugin.manager.feeds.handler:
    class: Drupal\feeds\Plugin\Type\FeedsPluginManager
    arguments: ['handler', '@container.namespaces', '@cache.cache', '@language_manager', '@module_handler']
  access_check.feeds.feed_add:
    class: Drupal\feeds\Access\FeedAddAccessCheck
    arguments: ['@entity.manager']
    tags:
      - { name: access_check, applies_to: _feeds_feed_add_access }
  feeds.subscription.crud:
    class: Drupal\feeds\PuSH\Subscription
    arguments: ['@database', 'feeds_subscription']
  feeds.subscription.controller:
    class: Drupal\feeds\Controller\SubscriptionController
    arguments: ['@feeds.subscription.crud']
  feeds.job_controller:
    class: Drupal\feeds\Controller\JobController
    arguments: ['@state', '@lock']
